source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

target ‘SwiftCocoapodsTest’ do

pod 'Alamofire'
pod 'MJRefresh','~> 3.3.0'
pod 'Kingfisher'
pod 'SwiftyJSON','~> 5.0.0'
pod 'DZNEmptyDataSet'
pod 'MBProgressHUD','~> 1.1.0'
pod 'ReachabilitySwift'
pod 'IQKeyboardManagerSwift', '~> 6.5.5'
pod 'SnapKit'
pod 'KeychainAccess', '~> 4.1.0'

end
